language: viml

sudo: false
dist: trusty

os:
    - linux

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install vim --HEAD; fi
    - vim --version
    # - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
    # - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
    - git clone https://github.com/thinca/vim-themis

script:
    - pip install vim-vint --upgrade
    - vint --version
    - vint autoload
    # - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL103=1 -e EVL102.l:_=1 autoload
    - vim-themis/bin/themis --reporter spec
